# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f99521eb5813f6e0c1b87ea483251755ad02be9efbe481e080d34920174d8299899d1ef0ea86f49afad23eeecfbe543e3ca99a847d808076e00ba99a8f1a3c

test:
  secret_key_base: 1ec42a4676a0d8c2128684fada706a6e1d19fac70b69f036b21e73663f37b5adbf91531ee755d1e0890e54a11235296994d6bf5f3ef8b365adad2face6451243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
